# Generated by Django 4.0.5 on 2022-07-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social1', '0004_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='some_hash',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
