# Generated by Django 4.0.5 on 2022-07-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social1', '0006_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='some_hash',
        ),
    ]
